version: '2'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    hostname: ${hostname}
    restart: unless-stopped
    entrypoint: []
    command: ["sh", "-c", "/filebrowser --username $${username} --password $$(/filebrowser hash $${password})"]
    ports:
      - "8080:80/tcp"
    expose:
      - 80
    environment:
      - username
      - password
      - FB_ADDRESS=0.0.0.0
      - FB_PORT=80
      - FB_ROOT=/srv
      - FB_DATABASE=/filebrowser.db
      - FB_LOGS=stdout
    volumes:
      - ./files:/srv
      - ./filebrowser.db:/filebrowser.db

