version: '2'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    hostname: ${hostname}
    restart: unless-stopped
    entrypoint: []
    command: ["sh", "-c", "/filebrowser --username $${username} --password $$(/filebrowser hash $${password})"]
    expose:
      - 80
    environment:
      - username
      - password
      - VIRTUAL_HOST=${hostname}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${hostname}
      - LETSENCRYPT_EMAIL
      - FB_ADDRESS=0.0.0.0
      - FB_PORT=80
      - FB_ROOT=/srv
      - FB_DATABASE=/filebrowser.db
      - FB_LOGS=stdout
    volumes:
      - ./files:/srv
      - ./filebrowser.db:/filebrowser.db
    network_mode: bridge
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
